#!/usr/bin/env python
# encoding: utf-8
# Author: C0D3DG0D - Alan Ramalho [ramalho.sit@gmail.com]

import os
import click

if (os.getuid() != 0):
    print("Please run this tool at root!")
    exit()
else:
    pass

click.echo("""Bssidfinder v1.2 - (https://gitlab.com/raioramalho/bssidfinder)

Find BSSID Address of wireless networks.
Created by C0D3DG0D - Alan Ramalho [ramalho.sit@gmail.com]
I do not take responsibility for your actions.
""")

@click.command()
@click.option('-i', '--iface', 'iface', default=None, help='Set your wireless usb card.')
@click.option('-e', '--essid', 'essid', default=None, help='Set the wireless ap name than you find.')

def main(iface, essid):
    if iface == None:
        click.echo("Usage: bssidfinder --help")
        exit()
    else:
        pass
    if essid == None:
        os.system("iwlist "+str(iface)+" scanning | egrep 'Cell |ESSID|Address' | sed 's/Cell//g'")
    elif essid != None:
        os.system("iwlist "+str(iface)+" scanning | egrep 'Cell |ESSID|Address' | sed 's/Cell//g' | grep -B 1 "+str(essid)+"")
    else:
        main()

main()

